### ISSUE TITLE
Navigation is generating additional module

### ISSUE THREAD

**Issue by NapkinHD** [allenhwkim/angular-jsdoc#103]
After generating the documentation, there is an additional entry called "module:app" in the navigation. I dont want it there and I do not even have a module called like this.
In particular the "module: app" with the "overview" and the subpoint "home" appears. But I'd like to have the point "overview" in the "module: app.home". How can I achieve this?

![unbenannt](https://cloud.githubusercontent.com/assets/10994581/18990899/7bae1aaa-8715-11e6-8d89-357200c816fa.PNG)

```
/**
 * @ngdoc overview
 * @name app.home
 * @description This module is very important
 */
angular.module('app.home', [])

    /**
     * @ngdoc controller
     * @name HomeCtrl
     * @memberOf app.home
     * @description controller returns 'hello world'
     * @param $scope {service} controller scope
     * @param $q {service} promise service
     */
    .controller('HomeCtrl', /*@ngInject*/ ["$scope", function ($scope, $q) {

        /**
         * @memberOf HomeCtrl
         * @function helloWorld
         * @description Returns hello world as a string
         * @returns {String} string
         */
        function helloWorld () {
            return 'hello world';
        }

    }])

    /**
     * @ngdoc controller
     * @name HomeCtrl2
     * @memberOf app.home
     * @description very important controller
     * @param $scope {service} controller scope
     */
    .controller('HomeCtrl2', /*@ngInject*/ ["$scope", function ($scope) {

    }])

/**
 * @ngdoc service
 * @name ImportModal
 * @memberOf app.home
 * @param {service} $q promise service
 * @description Important service
 */
.factory('ImportModal', /*@ngInject*/ function ($q) {
...
```

I've already tried to add "@memberOf app.home" to the first comment, but that did not work.
Is this a bug, or is it supposed to be that way?

**Comment by Faibk** [comment]
You need to name the overview. When you specify the @name annotation it will assume, that the last part is the name and the part before the point the module it's connected to.
That means you need to set @name like this:

```
@name app.home.myName
```
