### ISSUE TITLE
Trouble generating docs with links to line numbered source files

### ISSUE THREAD

**Issue by IgalOre** [allenhwkim/angular-jsdoc#11]
Hello, i had introduced usage of JSdoc with your template, and so far got nearly 100% satisfying results, except of one annoying thing:

In generated HTML pages, there no single link to numbered source files.
Numbered Source files are generated, i can open them in browser.

I had tried to use original default JSDoc template, and then those links to appears. Also i see that at your example [GoogleMaps](https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/index.html) those links are in place.

I'm using latest published at NPMJS [0.3.2](https://www.npmjs.com/package/angular-jsdoc) version of template.

Can you suggest what that could be ?

**Comment by allenhwkim** [comment]
![image](https://cloud.githubusercontent.com/assets/1437734/6987798/544266b0-da19-11e4-96e3-b9e878e607de.png)

As you see the above image.
The link to the source code is in two place. One is in 'Source: .....'  and the other is in '(static) link(scope, element, attrs)' as a link. I thought the first one is redundant, thus removed it. It was intentional, hopefully this does not bother many.

**Comment by allenhwkim** [comment]
You are right, it only generate source code for the object. It does not generate links for its methods. I will make a fix soon

**Comment by IgalOre** [comment]
Sorry for late reply, but even by adding `@function` tag still in generate documentation no links to source files.

May be this due to nature of our project that we documenting, AngularJS modules, services and contained functions in them, and that somehow forcing publishing script to forget generate pointers to numbered source files.

I will try to debug this issue in couple of weeks after my vacation period.

**Comment by allenhwkim** [comment]
Started rewriting of the whole template using AngularJS template `anuglar-template` with branch of `ngTemplate`.

**Comment by allenhwkim** [comment]
This is fixed with new release. 1.0.8
