### ISSUE TITLE
How to ignore specific files?

### ISSUE THREAD

**Issue by luninroman** [allenhwkim/angular-jsdoc#116]
How to ignore specific files? I have .spec.js files that placed next to my original AngularJS files. I want all of them to be ignored, because they were recognized as classes, that belongs to `undefined` module.

I've tried something like this, which gives an error.

```
gulp.task('docs', shell.task([
  'node_modules/jsdoc/jsdoc.js '+
  '-c node_modules/angular-jsdoc/common/conf.json '+
  '-t node_modules/angular-jsdoc/angular-template '+
  '-d ngdoc '+
  '-r web/assets/js/component/**/!(*spec).js'
]));
```

**Comment by allenhwkim** [comment]
You need to create your own conf.json starting from `https://github.com/allenhwkim/angular-jsdoc/blob/master/common/conf.json`

FYI
http://usejsdoc.org/about-configuring-jsdoc.html
http://usejsdoc.org/about-commandline.html

**Comment by luninroman** [comment]
@allenhwkim Thank you! Works for me
