### ISSUE TITLE
@member/@private disables documentation generation

### ISSUE THREAD

**Issue by SamuelMS** [allenhwkim/angular-jsdoc#13]
Hey @allenhwkim,

Thanks for creating this great template. I've found it remarkably useful.

However, it looks like certain tags will disable documentation generation for entries where present -- so far, I have encountered the issue with **``@member``** and **``@private``**. All other documentation will still be generated; it will simply skip entries with these tags.

Example:

    /* globals angular:false */
    
    'use strict'

    /**
     * @ngdoc service
     *
     * @name app.notYourTypicalService
     * @description Doesn't really do anything. Oh well.
     * @memberof app
     * 
     * @member {boolean} _superSecretPrivateVariable
     * 
     * @ngInject
     */
    function notYourTypicalService() {

        /**
         * @name _superSecretPrivateVariable
         * @description Indicates whether an email is currently being sent.
         * @type {boolean}
         * @private
         */
        var _superSecretPrivateVariable = false;

        return {
            // stuff
        };
    }
    
    angular.module('app').factory('notYourTypicalService', notYourTypicalService);

In the above example, the ``notYourTypicalService`` service will fail to be documented due to its use of the ``@member`` tag.

Similarly, even if the service were documented, the _superSecretPrivateVariable member will fail to be documented due to its use of the ``@private`` tag.

As soon as these offending tags are removed, documentation will successfully generate.

Is this intentional or am I missing something?

Thanks!

**Comment by allenhwkim** [comment]
Thanks for using this. 
I do not have intention not to generate documentation for `@private` and `@member`

JSDoc says `@private` won't generate documentation, http://usejsdoc.org/tags-private.html

`Private members are not shown in the generated output unless JSDoc is run with the -p/--private command-line option.`

Thus if you want to generate those, please make your own gulp file for that.
