### ISSUE TITLE
How can I use prettify-jsdoc and prettify-tomorrow?

### ISSUE THREAD

**Issue by robertbaker** [allenhwkim/angular-jsdoc#14]

**Comment by allenhwkim** [comment]
As you see here it's using template `node_modules/angular-jsdoc/template`.
You can copy this directory to yours and modify it for your own. e.g. `node_modules/angular-jsdoc/prettify-template`

```
var shell = require('gulp-shell'); 
gulp.task('docs', shell.task([ 
 'node_modules/jsdoc/jsdoc.js '+ 
   '-c node_modules/angular-jsdoc/conf.json '+   // config file
   '-t node_modules/angular-jsdoc/template '+    // template file
   '-d build/docs '+                             // output directory
   './README.md ' +                              // to include README.md as index contents
   '-r app/scripts'                              // source code directory
])); 
```

You may ask 'what if angular-jsdoc get upgraded?'. 
It's only css, and it does not change a lot of features.

The best wat is to modify prettify-jsdoc.css and prettify-tomorrow as I did it with default css.
I may do it in the future, but no guarantee.

You need to know is that default css is modified to make it work with html together.
If you want to use different css, you also need to make your own css.

**Comment by robertbaker** [comment]
Thanks,

I think I'll use tomorrow-dark http://jmblog.github.io/color-themes-for-google-code-prettify/tomorrow-night/

Could you add that to your repo?

**Comment by allenhwkim** [comment]
started a new branch `ngTemplate` by rewriting the existing template.

**Comment by allenhwkim** [comment]
This is fixed with new release. 1.0.8. You can have your own css by creating your own template.
