### ISSUE TITLE
Example links broken

### ISSUE THREAD

**Issue by Ryuno-Ki** [allenhwkim/angular-jsdoc#22]
Due to a change in your directory structure in [angularjs-google-maps](/allenhwkim/angularjs-google-maps/), your example links are broken.

They should point to https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/map.js and https://github.com/allenhwkim/angularjs-google-maps/blob/master/services/attr2_options.js (Pro Tipp: Hitting `y` will generate an even more stable URL by changing tree with commit!)

**Comment by allenhwkim** [comment]
Thanks for report it. I have update the README.md
