### ISSUE TITLE
On smaller screens, the nav overlaps the content

### ISSUE THREAD

**Issue by DidierLoiseau** [allenhwkim/angular-jsdoc#23]
The generated documentation only displays properly on large screens/browser windows.

See screenshot:
![angular-jsdoc-nav-overlaps-content](https://cloud.githubusercontent.com/assets/6871742/9271761/cda235a0-427c-11e5-8271-d5c202a100ae.png)

**Comment by allenhwkim** [comment]
This is fixed with new release. 1.0.8
