### ISSUE TITLE
trouble with group by

### ISSUE THREAD

**Issue by ss-bb** [allenhwkim/angular-jsdoc#24]
Hi. 
the group by @ngdoc is currently ineffective, all result are put in a "global" section, 

while i follow your googlemap Documentation style, my file start with 
/**
*@ngdoc controller (or service or ...)
*/
 I can't understand this behaviour. 

![tmp](https://cloud.githubusercontent.com/assets/5887682/9274768/a87763ec-4298-11e5-9035-fe7d9a19e5d7.png)

I use jsdoc/angular-jsdoc with command line on Windows *. 
options are -c node_modules/angular-jsdoc/conf.json -t node_modules/angular-jsdoc/template.

Do you have any hint? Maybe you need more detail?

**Comment by allenhwkim** [comment]
This is fixed with new release. 1.0.8
