### ISSUE TITLE
Error on running JSdoc with angular-jsdoc 1.0.8

### ISSUE THREAD

**Issue by IgalOre** [allenhwkim/angular-jsdoc#25]
Hello,

I just updated angular-jsdoc to 1.0.8, but now on execution generation of JSDoc got next error:
FATAL: Unable to load template: Cannot find module 'node_modules/angular-jsdoc/template//publish'

npm-debug.log doesn't contains any new information about error.

Since move to angular-template, is there any additional includes to add at package.json ?

**Comment by allenhwkim** [comment]
sorry about that. have changed the path and update the README.md
```
    // or you can run in command line
    $ node_modules/jsdoc/jsdoc.js \
      --configure node_modules/common/test_conf.json \
      --template node_modules/angular-jsdoc/default \
      --destination docs \
      --readme README.md \
      --recurse sample-codes
```

**Comment by allenhwkim** [comment]
@IgalOre Thanks for the reporting, and it's fixed now.
