### ISSUE TITLE
@param tag

### ISSUE THREAD

**Issue by DavideVar** [allenhwkim/angular-jsdoc#28]
Hi,
I'm using your tool to document an AngularJS project.
I have this issue: it seems that parameter (@param) loses its advanced properties: if I write this code,
    /**
         * @memberof odataQueryServiceFactory
         * @description Genera l'opzione di ordinamento di una query
         * @param {string} ordersby - Elenco criteri di ordinamento da applicare
         * @param {string} filter.key - Nome del campo da ordinare
         * @param {string} filter.criteria - Criterio di ordinamento asc|desc (se non specificato default e' asc)
         * @returns {string} - clausola $orderby dove la clausola e' $orderby=[clausola]
         */

I get this result:

getQueryOptionsOrderby (ordersby, filter.key, filter.criteria) -> string

filter.key	string	
Nome del campo da ordinare
filter.criteria	string	
Criterio di ordinamento asc|desc (se non specificato default e' asc)

As you can see, the field.key is considered as a new parameter and not as a property of filter.

Also if I write @param {string|Object} value, in the documentation I get only "string" as type of the variable.

I used the command line as suggested by you:

PS C:...> node C:...\node_modules\jsdoc\jsdoc.js --template C:....\node_modules/angular-jsdoc/default --configure  C:....\node_modules/angular-jsdoc/common/conf.json C:...\fileName.js

Can you please me tell me how can I solve this? 
Thank you

**Comment by allenhwkim** [comment]
could you add .js file here, so that I can regenerate document?

**Comment by allenhwkim** [comment]
added sample .js and resolved multiple param types with the release of 1.1.5

**Comment by DavideVar** [comment]
I'm sorry but I haven't got it with me at the moment, since it is at my
office and now I am at home. I will be at the office on monday and I will
send it to you.
Regards
Davide Varini
Il 28/ago/2015 08:41 PM, "Allen Kim" <notifications@github.com> ha scritto:

**Comment by DavideVar** [comment]
Hi Allen,

I attach you a file with some code snippets (and the resulting
documentation) with the following features regarding parameters:
- type as {type1|type2|type3} -> output=type a (method: getQueryResourceKey)
- parameter1, parameter1.a, parameter1.b -> output=3 parameters (even in
the method definition, where I have 1 only param) (method: getQueryOptions)
- Array: @param {string[}} -> output = Array.
 (method: getQueryOptionsExpand)
- Optional-> output=not considered optional. (method:
getQueryOptionsOrderby)

The code has been reduced and modified since it is protected by copyright
(sorry about that).

Here is the command line I used to produce the documentation:

node jsdoc.js --template [..]node_modules/angular-jsdoc/default --configure
 [..]node_modules/angular-jsdoc/common/conf.json [..]odataHelpersModule.js

Please let me know if you need anything more.

Thank you

Davide

2015-08-29 21:42 GMT+02:00 Davide Varini <varini.davide@gmail.com>:

**Comment by allenhwkim** [comment]
I am pretty sure this issue is resolved with new release. 
If the issue continues, please create a new ticket with your source code attached.
