### ISSUE TITLE
Question:  how do I get relative paths to show instead of full paths

### ISSUE THREAD

**Issue by DaClan008** [allenhwkim/angular-jsdoc#30]
I am currently using "Or, With Gulp" option almost verbatim as per your example.  However if I click on the source button.  I see the full path of the file.  i.e. c:\ .....\folder\file.js.  Is it possible to use relative paths i.e. only \folder\file\js?

**Comment by allenhwkim** [comment]
As you see in the generated document, it does not use absolute path for `href` attribute.
https://github.com/allenhwkim/angular-jsdoc/blob/master/default/docs/ngmap.MapController.html#L42

`        <a class="name-link signature-attributes" href="source/ngmap.MapController.html#line4">source</a>`

This is the working example, and check the html source code.
https://rawgit.com/allenhwkim/angular-jsdoc/master/default/docs/ngmap.MapController.html

**Comment by DaClan008** [comment]
wow... thanks for the quick response.  And I think I did not ask the question correctly.  My problem is not with the href part, but the part that shows up as header when you navigate to the source.  i.e. This header:
![ang](https://cloud.githubusercontent.com/assets/8425436/9755393/fe648f4e-56d1-11e5-8208-8a73d52713c2.png)
On my system this header would show up as-> Source:C: \ ..... folder\map-controller.js.  is it possible to restrict this header only to a relative path and the file name?  I should also perhaps state that all my .js files is situated in [jsfolder / folder / file.js].  on the "gulp settings" the watch then looks like this: -r jsfolder.  All the files do get compiled ok and it works perfectly.  It is just the header that pushes everything out of proportion and the fact that it will be incorrect when the project is run on some other system.  

It will be great to show relative paths too, if not then maybe as a start only the name of the file?
Thank you Allen.

**Comment by DaClan008** [comment]
Sorry... I clicked the wrong button... it's not closed -> not sure how to remove that now :(

**Comment by allenhwkim** [comment]
Interesting, is it a Windows thing? Could you try to use relative path for your command, or add you gulp task here, so that I can see it. I do not have windows, so I may need other's help.

**Comment by DaClan008** [comment]
Well I do run it from windows... but not sure if that is the problem?  I thought there was only an option to set which path variable to use.  Here is my gulp extract:

    gulp.task('docs2', shell.task([
        'jsdoc '+
        '-c xDoc/conf.json ' +                                      // config file
        '-t node_modules/angular-jsdoc/angular-template ' +         // template
        '-d doc3 ' +                                                // out directory
        './README.md ' +                                            // Readme file
        '-r tmp/scripts'                                            // source code directories (space deliminated)
    ]));

Within my tmp/scripts folder there are for instance a Directives folder and a Services folder etc etc.
Here is a quick output of an example source page:


![docs](https://cloud.githubusercontent.com/assets/8425436/9776736/d5f0603a-575b-11e5-9c57-8ba6b61bc9c1.png)
:

**Comment by allenhwkim** [comment]
Patch has been implemented and released as version 1.1.6

**Comment by DaClan008** [comment]
Hi Allen.  That definitely solved the issue.  Thank you!!! I will mark this issue as closed.
