### ISSUE TITLE
can't doc the sample-codes dir nor little project.

### ISSUE THREAD

**Issue by ss-bb** [allenhwkim/angular-jsdoc#31]
Hi. 

Maybe it's me, but i can't run the doc on my real project (nor on the "sample-code directory") using a fresh install of ubuntu 14, node & npm,

using node or command line. All appear to be good in the console, but NO directory/file are create (on a very basic project).
using gulp (with all depency) on the sample-code dir with the given gulpfile render : "Task 'default' is not in your gulpfile".

once again, It's friday and I suppose I get dumb. Can somebody just confirm it's OK for them with the new angular-jsdoc.

Thank. Have a nice day.

**Comment by allenhwkim** [comment]
`npm test` runs fine?

**Comment by ss-bb** [comment]
Hi. 
Thank a lot, it's OK now. 
My bad thank to `npm test` : I forgot to add js-template & angular-template in my node_module.
