### ISSUE TITLE
@memberof function

### ISSUE THREAD

**Issue by dkromp** [allenhwkim/angular-jsdoc#34]
Hi, 
I have a controller with a function that has a function within the controller. How is this best documented?

**Comment by allenhwkim** [comment]
could you provide an example?

**Comment by dkromp** [comment]
How should I best document bar function:

var myApp = angular.module('myApp',[]);

myApp.controller('GreetingController', ['$scope', function($scope) {
  function foo(){
    bar();
     function bar(){}
}
}]);

**Comment by allenhwkim** [comment]
You can do like this, http://stackoverflow.com/questions/19230971/how-do-i-jsdoc-a-nested-objects-methods

However, I recommend to keep the whole structure as flat as possible for a class. For your case, bar function can be defined outside of foo() function. IMO,  It is not a good practice to make nested properties and nested functions.

```
angular.module('myApp',[]).controller('fooCtrl', ['$scope', function($scope) {
  var bar = function() {
  };
  var foo = function() {
     bar(); // run bar function
  };
}]);
```

**Comment by dkromp** [comment]
Good advice. thx!
