### ISSUE TITLE
Tutorials support

### ISSUE THREAD

**Issue by yodiman** [allenhwkim/angular-jsdoc#36]
Jsdoc has [tutorials](http://usejsdoc.org/about-tutorials.html) functionality, but angular-jsdoc has not. It would be nice if this functionality has been added.

**Comment by darkmavis1980** [comment]
+1
I have the same issue, and I had an older version and it was working before.
That's what I get now

![screen shot 2015-11-17 at 11 38 45 a m](https://cloud.githubusercontent.com/assets/2980681/11210390/c7c2bd2e-8d1f-11e5-8c61-a633b57b5c81.png)

**Comment by allenhwkim** [comment]
Added tutorial feature with 1.3.0 release with angular-template

**Comment by darkmavis1980** [comment]
It would be possible to have it on the default template as well? The angular-template doesn't really work for my project

**Comment by allenhwkim** [comment]
version 1.3.1, tutorials are added for default template.

**Comment by darkmavis1980** [comment]
@allenhwkim thanks!

**Comment by darkmavis1980** [comment]
Just tried, but still the tutorial links are not working

**Comment by allenhwkim** [comment]
This is what I have tested.

Input
https://github.com/allenhwkim/angular-jsdoc/blob/master/sample-codes/app/custom-currency.js\

Output
https://rawgit.com/allenhwkim/angular-jsdoc/master/default/docs/app.customCurrency.html

**Comment by allenhwkim** [comment]
closing. Please reopen this if not resolved
