### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by KevinDennyII** [allenhwkim/angular-jsdoc#37]
After running 'node node_modules/jsdoc/jsdoc.js -c node_modules/angular-jsdoc/common/conf.json', we were able to properly produce our html jsdocs except for the index.html.

Any possible idea of what could be causing this issues?

**Comment by allenhwkim** [comment]
Do you have README.md?

**Comment by KevinDennyII** [comment]
Yes

**Comment by allenhwkim** [comment]
As you see here, 
`node_modules/jsdoc/jsdoc.js --configure common/test_conf.json --template angular-template --destination angular-template/docs --readme sample-codes/README.md --recurse sample-codes`

This --readme has to be there to make index.html
` --readme sample-codes/README.md`

**Comment by KevinDennyII** [comment]
Oh ok.  Thank for clarifying that.  I am a bit new to this stuff.

**Comment by KevinDennyII** [comment]
So i doubled checked and yes, the readme file actually was already there as I did do the changes as stated in the instructions....
