### ISSUE TITLE
Object property - Angular Template

### ISSUE THREAD

**Issue by gianx89** [allenhwkim/angular-jsdoc#38]
Hi, I want to comment o property of an object using angular template, see code below:

```
return $resource(AppService.getServerAddress() + "/media/file/thumbnail/:media_id",
    {media_id: '@media_id'},
    {
        /**
         * @property {object} Thumbnail
        */
        query: {
            method: 'GET',
            timeout: 120000
        }
    })
```

But I can't find any trace of the property in the generated docs. Can someone help me?

**Comment by allenhwkim** [comment]
Please add `@memberof`

**Comment by gianx89** [comment]
I have that code inside a factory. I should use @memberof and? The name of the function?

**Comment by allenhwkim** [comment]
@memberof Class name, not function name

**Comment by allenhwkim** [comment]
You can see example code in sample-codes/app/test-service.js
