### ISSUE TITLE
How do you document a module's config function?

### ISSUE THREAD

**Issue by dkromp** [allenhwkim/angular-jsdoc#39]
How do you document a module's config function?

    /**
      * Controls header
      * @memberof app.header
      * @ngdoc config      <---- not available in ngdoc
      */

**Comment by allenhwkim** [comment]
I don't know, I need to see your code in your file. There are sample-codes that you can take a look at 
https://github.com/allenhwkim/angular-jsdoc/tree/master/sample-codes

**Comment by dkromp** [comment]
Here you are:

    (function () {
        'use strict';

        angular
	    .module('app')
	    .config(stateConfig)

       /**
        * Configures ui-router's states.
        * @memberof app
        * @ngdoc config
        * @name config
        * @param {Service} $urlRouterProvider Watches $location and provides interface to default state
        */

        function stateConfig($urlRouterProvider) {
            $urlRouterProvider.otherwise('/search')
        }
    })();

**Comment by allenhwkim** [comment]
I added your code into sample-codes/app/config.js and generated the documentation, and I see like this.

![image](https://cloud.githubusercontent.com/assets/1437734/11551939/337d55f0-994c-11e5-90b9-874d980e95a8.png)

**Comment by dkromp** [comment]
perfect - i think i was under /overthinking things =P.
