### ISSUE TITLE
Correction to gulp task

### ISSUE THREAD

**Issue by dkromp** [allenhwkim/angular-jsdoc#40]
replace 'node_modules/jsdoc/jsdoc.js' with 'jsdoc'

    var shell = require('gulp-shell');
    gulp.task('docs', shell.task([
      'jsdoc '+
        '-c node_modules/angular-jsdoc/common/conf.json '+   // config file
        '-t node_modules/angular-jsdoc/angular-template '+   // template file
        '-d build/docs '+                           // output directory
        './README.md ' +                            // to include README.md as index contents
        '-r directives services'  +                 // source code directory
        '-u tutorials'                              // tutorials directory
    ]));

**Comment by allenhwkim** [comment]
Closing. jsdoc is not always installed in global level.
