### ISSUE TITLE
angular-template ul nav groups expand every time you change pages

### ISSUE THREAD

**Issue by dkromp** [allenhwkim/angular-jsdoc#41]
Using the angular-template that comes with angalar-jsdoc, the ul nav groups expand every time you change pages. This makes for a very distracting user experience. Let me know if you have a quick fix.

**Comment by allenhwkim** [comment]
I don't understand the issue. Each page is a separate page and reload every single time when you cash age pages. An example would be helpful to understand your issue.

**Comment by dkromp** [comment]
1. With angular-template, click a header for any of the nav links on the right side of the page.
    1a. The selected header will hide nested content and display icon next to text indicating children links are hidden. 
2. From nav, select a non-header link.
    2a. A new page will load for the selected link, and the nav will show ALL links.  <-- the nav should not change to show all nested children links.

**Comment by allenhwkim** [comment]
Thanks I will take a look at it. There might be a bug in it

**Comment by allenhwkim** [comment]
This is not a but. It was built like this to. We can improve this feature to unflod the document only, and closing all others.

**Comment by allenhwkim** [comment]
I will close this. If more request are made about this feature, I will consider implementing this feature.
