### ISSUE TITLE
Factory/service properties (how to)

### ISSUE THREAD

**Issue by coryasilva** [allenhwkim/angular-jsdoc#44]
Hello, I am having trouble documenting some mutable properties on a service.

In the example below how would I document `obj` and `bool`.  I am a little new to jsdocs but and I have tried using `@member`, `@memberof!`, and `@property` to no avail.

    /**
     * @memberof app
     * @ngdoc service
     * @name appService
     * @param {service} $http A core Angular service that facilitates communication with remote HTTP servers
     * @description
     *   Provides methods and stuff
     */
    angular.module('app')
        .factory('appService', function ($http) {
            var obj = {
                a: 'b'
            };
            var bool = true;
            var service = {
                obj: obj,
                bool : bool ,
                query: query
            };
            return service;
            /**
             * Query Stuff
             * @memberof appService
             * @param {string} id The `id` of the thing
             * @return {Promise}
             */
            function query(id) {
                if (!bool) { return; }
                return $http.get(obj.a + id);
            }
        })
    ;

PS Thanks for opening this package to all of us.

**Comment by Siqu** [comment]
Inside of my code is use following syntax:

e.g. for obj
```
/**
 * @memberof appService
 * @property {object}
 * @description
 *   Provide a description was the property does.
 */
var obj = {
    a: 'b'
};
```

It will render following html:

<div class="members">
  <h3 class="subsection-title">Members</h3>
  <dl>
    <dt>
      <a href="#" class="name-link">
        <h4 class="name">obj</h4>
      </a>
    </dt>
    <dd>
       <div class="description"><p>Provide a description was the property does.</p></div>
    </dd>
  </dl>
</div>

Currently it will not display the properties type - i think it wouldn't be very hard to adapt the angular-template to display it next to the name.

**Comment by allenhwkim** [comment]
1.3.2 is updated with this change. Please checkout the sample codes, especially testService.

**Comment by coryasilva** [comment]
Awesome, thank you guys!
