### ISSUE TITLE
Hidden main title on index.html

### ISSUE THREAD

**Issue by Mic75** [allenhwkim/angular-jsdoc#45]
Hi,

First of all, thanks for angular-jsdoc, it makes doc generation for angular much more easy.
I have noticed this small issue:

With the new suggested template `node_modules/angular-jsdoc/default`,  the main title of the index page get colored in white. Problem is that the background is white too, making the text invisible.

![title_issue](https://cloud.githubusercontent.com/assets/1568791/11965667/150f48b2-a8c4-11e5-87ce-78155da4d087.jpeg)
![title_issue2](https://cloud.githubusercontent.com/assets/1568791/11965669/19b7c628-a8c4-11e5-9885-09709ffe30a1.jpeg)

**Comment by allenhwkim** [comment]
Thanks for reporting this. it's fixed with v1.3.3
