### ISSUE TITLE
@ngdoc event

### ISSUE THREAD

**Issue by kfirzuberi** [allenhwkim/angular-jsdoc#46]
In the default template file 'class.html' there is no events list.

**Comment by allenhwkim** [comment]
I do not understand this requirement. Please be specific.

**Comment by kfirzuberi** [comment]
Hi!

I meant that there is no any reference to ```@ngdoc event``` tag.

How is solved it?

In the template ```class.html``` file I added:
```javascript
 <div class="events" ht-if="children.event">
        <h3 class="subsection-title">Events</h3>
        <dl ht-repeat="evt in children.event">
          ...
        </dl>
</div>
```

**Comment by Zemke** [comment]
Will be continued in #63.
