### ISSUE TITLE
automatically ignore the controller or support @ignore

### ISSUE THREAD

**Issue by noelmace** [allenhwkim/angular-jsdoc#55]
Following the Angular2 migration guidelines, I wrote this es6 code : 

```
'use strict';

/**
 * @ngdoc directive
 * @memberof example.layout
 * @name layoutFooter
 * @description
 *  Global footer for the application
 */
angular.module('example.layout')
    .directive('layoutFooter', () => {

        /**
         * @namespace
         * @ignore
         */
        class LayoutFooter {

            constructor() {
                // TODO
            }
        }

        return {
            restrict: 'EA',
            scope: {},
            bindToController: {},
            controller: LayoutFooter,
            controllerAs: 'layoutFooter',
            templateUrl: 'layout/layout-footer_component.html'
        };
    });

```

For now, angular-jsdoc create a new page for the controller classe, with an undefined module. I tried everything, but nothing seems to work on this element.

**Comment by allenhwkim** [comment]
I cannot answer this. angular-jsdoc follows JSDoc3 and I don't think JSDoc 3 understands ES6 syntax, AFAIK

**Comment by noelmace** [comment]
Jsdoc 3 does support ES6 class : http://usejsdoc.org/howto-es2015-classes.html
https://github.com/jsdoc3/jsdoc/issues/555

But, even if my example is in ES6, if you write this with es5 (by simply using function instead of class), the problem is the same.

**Comment by reloaded** [comment]
I can look into adding support for @ignore @noelmace

**Comment by noelmace** [comment]
PR & Issues spring-cleaning: I no longer face the problem, and the discussion on this topic is no longer active, so I close this issue / PR. Feel free to reopen it if necessary.
