### ISSUE TITLE
Troubles viewing source

### ISSUE THREAD

**Issue by IgalOre** [allenhwkim/angular-jsdoc#56]
Hello,

We had upgraded to angular-jsdoc 1.3.3, when realized that few things become broken on attempt to use 'angular-template' template:

* Modules in application using dot to separate name in namespace looking like _wkfsfrc.ui.widgets_ ; generated documentation looking pretty and nice, but all underlying service and directives sources link are wrong.
In name of each service/directive there an # character , like wkfsfrc.ui.widgets#wkfsfrc-auto-height, rendering that source anchor also having it : 
`<a class="name-link signature-attributes" href="source/wkfsfrc_ui_widgets#wkfsfrc-auto-height.html#line4">source</a>`
where correct syntax should be 
`<a class="name-link signature-attributes" href="source/wkfsfrc_ui_widgets%23wkfsfrc-auto-height.html#line4">source</a>`

Strangely this does works by using default template.

* For some reason all { \@link } pointers to services implemented in same module had stopped working. 

For example, next `{@link wkfsfrc.ui.widgets#AutoHeightService}` would expect to create anchor to service implementation, that defined as this:
`
/**
     * @memberof wkfsfrc.ui.widgets
     * @ngdoc service
     * @name wkfsfrc.ui.widgets#AutoHeightService
     * @description
     * <p>
     *     Service for calculating automatically the height of a component based on the height of the screen and a specified margin. A margin will specify the number
     *     of pixels of the total screen height that the component will not use.
     *     Allowed margins can be defined by decorating the wkfsfrc.ui.widgets#AutoHeightMargins provider and returning an object containing properties
     *     for each margin.
     *     Ex.
     *          $provide.decorator('AutoHeightMargins', function($delegate) {
     *              return {'default': 300, 'narrow': 150};
     *          });
     * </p>
     */
`

This does not work on both templates (default and angular-template)

Will try to debug both issues later on during coming days, but if it sounds familiar or there some bright idea what those could be...

**Comment by IgalOre** [comment]
I had modified slightly publish.js of angular-template on line 247:
`    if (doclet.meta) {
      if (doclet.kind == 'class') {
        doclet.sourceUrl = 'source/'+
          encodeURIComponent(sourceCodes[doclet.name].longname)+
          ".html#line"+doclet.meta.lineno;
      } else if ( (doclet.kind == 'function' || doclet.kind == 'member') &&
        sourceCodes[doclet.memberof]) {
        doclet.sourceUrl = 'source/'+
          encodeURIComponent(sourceCodes[doclet.memberof].longname)+
          ".html#line"+doclet.meta.lineno;
      }
    }`

By adding _encodeURIComponent_ JS call on longname, and this does the magic for this.
Could this be incorporated in one of next releases ?

**Comment by Zemke** [comment]
This might have been fixed with [1.4.0](https://github.com/allenhwkim/angular-jsdoc/releases/tag/v1.4.0). If not, please reopen.
