### ISSUE TITLE
Code shown when exectuting JSDoc

### ISSUE THREAD

**Issue by darkmavis1980** [allenhwkim/angular-jsdoc#6]
Hi, every time I execute JSDoc with the angular-jsdoc plugin installed it returns this code:
```javascript
view { path: '/../node_modules/am-angular-jsdoc/template/tmpl',
  layout: null,
  cache: {},
  settings: 
   { evaluate: /<\?js([\s\S]+?)\?>/g,
     interpolate: /<\?js=([\s\S]+?)\?>/g,
     escape: /<\?js~([\s\S]+?)\?>/g } }
```
Any idea why? It doesn't prevent the documentation from being generated, but it's just annoying that every time I get that

**Comment by allenhwkim** [comment]
It's just annoying console message I haven't commented out.

    angular-jsdoc (master)$ grep -nri "console.log" ./
    .//template/publish.js:425:console.log('view', view);

If you have time, plz comment that out and send me a pull request. If you don't I will deal with it later.

**Comment by darkmavis1980** [comment]
Perfect, thanks!

**Comment by allenhwkim** [comment]
it's done, angular-jsdoc@0.3.2
please update the module

**Comment by darkmavis1980** [comment]
Thank you again

On 6 February 2015 at 00:35, Allen Kim <notifications@github.com> wrote:

> it's done, angular-jsdoc@0.3.2
> please update the module
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/allenhwkim/angular-jsdoc/issues/6#issuecomment-73160132>
> .
>



-- 
Alessio Michelini

http://musicphotographer.eu
Flickr at http://www.flickr.com/photos/darkmavis
Twitter: http://twitter.com/darkmavis1980
