### ISSUE TITLE
Have to explicitly define membership when inside IIFE, but not if not enclosed in IIFE

### ISSUE THREAD

**Issue by sjclemmy** [allenhwkim/angular-jsdoc#65]
If I declare my service definition in a file thus:

```
myParent.factory('fileplanState', fileplanState);

/**
 * @memberof myParent
 * @name fileplanState
 * @ngdoc service
 * @param $log
 */
function fileplanState ($log) {


  /**
   *
   * @returns {*}
   */
  function getFileplanRoot() {
//...code
}
```

The method description resolves automatically.

However if I wrap this code in an IIFE:
```
(function (myParent){
//put the above code in here...
})(myParent);
```
The method description for `getFileplanRoot()` disappears unless I add `@memberof fileplanState`

Any thoughts?

**Comment by sjclemmy** [comment]
So there's a bit of a catch 22 here. NOT wrapping in the IIFE means the function definition is on global scope which is bad, but the methods auto resolve which is good. However if you wrap it in the IIFE the function definition is not in global scope, which is good, but the JsDoc function descriptions do not auto resolve, which is bad.
Further, the only reason not to have the function definitions inline and anonymous is to support JsDoc. So if I wasn't using JsDoc I could leave the functions anonymous and inline and I wouldn't need to wrap in an IIFE.

**Comment by Zemke** [comment]
This is an interesting observation, @sjclemmy.

So, you’re saying that `@memberof` is obsolete when not wrapping in the IIFE, but it’s required when it’s wrapped in the IIFE?

If that’s the case, that would be worth the effort of fixing, since it saves the hassle of adding `@memberof`s.

**Comment by reloaded** [comment]
That would explain why I have to put @memberof for all of my doc blocks. I wonder if this is a bug or limitation with jsdoc itself?

**Comment by reloaded** [comment]
@Zemke  @sjclemmy  I discovered what's going on.

@sjclemmy  Replace `@name fileplanState` with `@name fileplanState` and everything will work just fine in the IIFE.

According to the `@name` JSDOC3 docs:

> Warning: By using the `@name` tag, you are telling JSDoc to **ignore the surrounding code and treat your documentation comment in isolation**. In many cases, it is best to **use the `@alias`** tag instead, which changes a symbol's name in the documentation but preserves other information about the symbol.

**Comment by sjclemmy** [comment]
@reloaded good find! That makes everything a lot better. The private properties now automatically resolve as Members. Thanks.
