### ISSUE TITLE
angular-jsdoc v1.4.0

### ISSUE THREAD

**Issue by Zemke** [allenhwkim/angular-jsdoc#67]
Could we publish the new release that I submitted for NPM as well as for this Git repo incl. the release notes that I added? Thanks!

**Comment by allenhwkim** [comment]
@Zemke Thanks for this, published
```
angular-jsdoc (master)$ git tag -l
v1.4.0
angular-jsdoc (master)$ npm publish
+ angular-jsdoc@1.4.0
angular-jsdoc (master)$
```

**Comment by Zemke** [comment]
Awesome! Thanks a lot!

I’m on NPM, my name over there is [zemke](https://www.npmjs.com/~zemke).

**Comment by allenhwkim** [comment]
```
angular-jsdoc (master)$ npm owner list
allenkim <allenhwkim@gmail.com>
zemke <flzemke@gmail.com>
```
