### ISSUE TITLE
using @property

### ISSUE THREAD

**Issue by markhayton** [allenhwkim/angular-jsdoc#68]
This shows up in Members but with no type or description in the table 
/** 
   * @memberof appController
   * @prop {object} $scope.scheduleData - The current schedule data object 
   */

You show in your map-controller this example, but it doesn't seem to generate anything in document output
/**
     * @property {Hash} _objects collection og objects that belongs to this map
     */

I have to do this to get all the data to fill in (which is verbose, I would like the one line @property like above
/** 
   * @memberof appController
   * @prop {object}
   * @type {object}
   * @description The current schedule data object 
   */

Thanks, I am really getting some good docs from this tool so far..

**Comment by Zemke** [comment]
What are you actually documenting? Could you include the code?

**Comment by Zemke** [comment]
Please reopen when you have further information.
