### ISSUE TITLE
@attr support with optional and default value syntax

### ISSUE THREAD

**Issue by reloaded** [allenhwkim/angular-jsdoc#73]
Most Angular JS directives have optional parameters with default values. JSDOC3 appears to support this detection so the templates should be updated so the directive "Attributes" table has two additional columns that specify optionality and default values.

```
* @attr {string} [type=select] The type of form widget to render, default value is "select". Supported values are: "select", "radio".
```

**Comment by Zemke** [comment]
This has been introduced with [1.4.0](https://github.com/allenhwkim/angular-jsdoc/releases/tag/v1.4.0).

Example:

```js
(function () {
  'use strict';

  /**
   * @ngdoc directive
   * @name appExampleDirective
   * @memberof app
   *
   * @restrict AEC
   * @scope {}
   *
   * @description
   * Test
   *
   * @param {string} [x]
   * @param {string} [y="nice"]
   * @param {string} z
   * 
   * @attr {string} [x]
   * @attr {string} [y="nice"]
   * @attr {string} z
   */
  angular
    .module('app')
    .directive('appExampleDirective', appExampleDirective);

  function appExampleDirective($timeout, ExampleDirective, ExampleDirectiveService, DATES) {
    return {
      restrict: 'AEC',
      scope: {
        filterColumn: '=',
        valueType: '@',
        pickerValue: '@',
        initialValue: '=?',
        physicalUnit: '=?'
      },
      link: linkFn
    };

    function linkFn(scope, elem, attr) {

      /**
       *
       * @memberof app.appExampleDirective
       * @param {string} [x]
       * @param {string} [y="nice"]
       * @param {string} z
       * @returns {null}
       */
      function test(x, y, z) {
        return null;
      }
    }
  }
})();

```

![screen shot 2016-04-21 at 10 32 01 pm](https://cloud.githubusercontent.com/assets/3391981/14723382/1f54013a-0811-11e6-9926-d021b05cdfc7.png)

**Comment by reloaded** [comment]
@Zemke I did notice that adding [x] and [x=string] did "work" in the sense that the attribute name was outputed to the "name" column. 

However, this issue (lack of details on my part) was meant to be an enhancement request to provide two additional columns and one change to the table.

The additional columns would be:
Required

- Required: The possible column values would be Yes or No
- Default: The possible column values would be the default value or a blank column. The default value should support either a default string or a default {@link myObject} or [], etc.

The additional change would be to show the attribute/parameter name without brackets and the default value. Using the sample screenshots you provided above it would be nice if the "Name" columns said "x" and "y" instead of "[x]" and "[y='nice']", respectively.

**Comment by allenhwkim** [comment]
I do not have official plan to support extra column do the table. Please use description for that purpose; optional/required

**Comment by reloaded** [comment]
Are you open to accepting a PR for this, assuming it's not on your road map due to time constraints?

**Comment by allenhwkim** [comment]
I want to keep all table to have the same structure; name, type, and description, unless provided a good reason to make an exception.
