### ISSUE TITLE
Modules, controllers and functions

### ISSUE THREAD

**Issue by bhauk67** [allenhwkim/angular-jsdoc#8]
I am trying to do something similar to your directive and service examples to produce documents, but also try to define a module either in the same js file or  two different files.

In either case, I have not been able to link the module, controller/service/factory and the functions they contain. If they are all in the same file, controller does not show the defined functions, and if they are in different pages, the module does not show the controller.

**Comment by allenhwkim** [comment]
This documentation is not for multi module, but for a single module. 
I do not see the need to document multiple modules in a single document. 
Unless I found a simple solution for that(you guys can help me), I want to keep it as it is.

**Comment by kikar** [comment]
I feel like according to main style guides using different modules is almost necessary for big apps.
They way you could implement it is:
* Modules defined  `@ngdoc moduleName`
* Every Controller/Directive/Service in that module uses `@memberOf moduleName`
* In the docs navigation have modules on top and then components of the module on the bottom.
    * If clicked on the module show only relative components

What do you think? Is it very difficult to implement?
