### ISSUE TITLE
Why type 'service' and 'MapController' fails to load on below url?

### ISSUE THREAD

**Issue by jsbimra** [allenhwkim/angular-jsdoc#84]
[https://rawgit.com/allenhwkim/angular-jsdoc/master/angular-template/docs/ngmap.map.html](url)

**Comment by Zemke** [comment]
The `service` type does simply not exist. You could create the service type like so:

```js
/**
 * @ngdoc type
 * @name service
 *
 * @description
 * Any service you could imagine.
```

It would then correctly link to the documentation of the type `service`.

As for `MapController`, it does exist, but it’s not correctly linked to. `MapController` exists in the `ngmap` module, the current documentation assumes it’s not in a deeper module structure. You’d need to prepend the module name like `@param {ngmap.MapController} ctrl map controller` to clarify that.

**Comment by jsbimra** [comment]
do I need to put `service` type code ? in separate file of same file were we define the `doc` for controller?

**Comment by Zemke** [comment]
You can put it anywhere.

**Comment by jsbimra** [comment]
ok thanks.
